### ISSUE TITLE
Path string parsing, needs `/` 

### ISSUE THREAD

**Issue by riveSunder** [riveSunder/bevodevo#13]
If you try to use plot or enjoy with a directory filepath that doesn't end in `/`, you get the following error. 

```
# command
python -m bevodevo.enjoy -n BackAndForthEnv-v0 -f results/GeneticPopulation_MLPBodyPolicy_p64_g100_s13_w3 -pi MLPBodyPolicy -a 1 -e 1 -s 1

# output
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "bevodevo/bevodevo/enjoy.py", line 227, in <module>
    enjoy(args)
  File "bevodevo/bevodevo/enjoy.py", line 35, in enjoy
    my_dir = os.listdir(argv.file_path)
FileNotFoundError: [Errno 2] No such file or directory: 'results/GeneticPopulation_MLPBodyPolicy_p64_g100_s13_w3'

```

**Comment by riveSunder** [comment]
Fix added in PR #14
